### 특정 직원의 현재 정보 조회
GET http://localhost:8080/employees/999999

### 특정 직원의 직무 이력 조회
GET http://localhost:8080/employees/123123/history

### 직원 정보 업데이트
PUT http://localhost:8080/employees/999999
Content-Type: application/json

{
  "firstName": "firstName",
  "lastName": "lastName",
  "email": "updated@email.com",
  "phoneNumber": "010.1234.5678",
  "hireDate": "2021-01-01",
  "salary": 5000,
  "commissionPct" : 0.8,
  "departmentId": 20,
  "jobId": "ST_CLERK",
  "managerId": 999999
}

### 부서 목록 조회
GET http://localhost:8080/departments

### 부서 급여 인상
POST http://localhost:8080/departments/salary?departmentId=999&percentage=-1

### 치과 목록 검색 (대전)
GET http://localhost:8080/dentist/search?pageNo=1&pageNum=10&region=DJ

### 치과 목록 검색 (대구)
GET http://localhost:8080/dentist/search?pageNo=1&pageNum=10&region=DE